misc:
  exp_dir: indoor
  mode: train
  gpu_mode: True
  verbose: True
  verbose_freq: 500
  snapshot_freq: 1
  pretrain: ''


model:
  model: ResUNetBN2C
  in_feats_dim: 1
  out_feats_dim: 32
  conv1_kernel_size: 5
  normalize_feature: True
  dist_type: L2

overlap_attention_module:
  gnn_feats_dim: 256
  dgcnn_k: 10
  num_head: 4
  nets: ['self','cross','self']

loss:
  pos_margin: 0.1
  neg_margin: 1.4
  log_scale: 24
  pos_radius: 0.0375
  safe_radius: 0.1
  overlap_radius: 0.0375
  matchability_radius: 0.05 
  w_circle_loss: 1.0
  w_overlap_loss: 1.0
  w_saliency_loss: 0.0
  max_points: 256

optimiser:
  optimizer: SGD
  max_epoch: 200
  lr: 0.1
  momentum: 0.8
  weight_decay: 0.0001
  bn_momentum: 0.05
  scheduler: ExpLR
  scheduler_gamma: 0.99
  scheduler_freq: 1
  iter_size: 4

dataset:
  dataset: indoor
  benchmark: 3DMatch
  root: data/indoor
  voxel_size: 0.025
  batch_size: 1 
  num_workers: 6 
  augment_noise: 0.005
  train_info: configs/indoor/train_info.pkl
  val_info: configs/indoor/val_info.pkl

demo:
  src_pcd: assets/cloud_bin_21.pth
  tgt_pcd: assets/cloud_bin_34.pth
  n_points: 1000

